apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"my-nginx-nginx-ingress-controller-76c6c54585-2ppgf","leaseDurationSeconds":30,"acquireTime":"2019-07-19T21:14:11Z","renewTime":"2019-07-19T21:15:49Z","leaderTransitions":0}'
  creationTimestamp: 2019-07-19T21:14:11Z
  name: ingress-controller-leader-nginx
  namespace: default
  resourceVersion: "1610"
  selfLink: /api/v1/namespaces/default/configmaps/ingress-controller-leader-nginx
  uid: 2772e851-aa6a-11e9-8636-42010aa80026
